#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
weather_in_city:
  path: /weather/{countryCode}/{cityName}
  controller: App\Controller\WeatherController::cityAction
  requirements:
    countryCode: '[A-Z]{2}'
    cityName: '[a-zA-Z- ]+'
  defaults:
    countryCode: 'PL'
    cityName: 'Goleniów'